CREATE TABLE IF NOT EXISTS waveData (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content BLOB NOT NULL,
    location TEXT NOT NULL
);
